# Generated by Django 5.1.1 on 2024-09-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Cats/')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
